packages:
  - apps/*
  - packages/*
catalog:
  typescript: ^5.5.2
  turbo: ^2.4.4
  "@biomejs/biome": ^2.0.6
  "@types/node": ^22.10.2
  "globals": ^15.6.0
  "tsup": ^8.0.2
  "tsx": ^4.15.7
  "vite-tsconfig-paths": 4.3.2

catalogs:
  utils:
    "@faker-js/faker": ^9.3.0
    dayjs: 1.11.13
  validation:
    zod: ^3.24.1
  testing:
    vitest: 1.6.0
    vitest-mock-extended: 1.3.1
    "@vitest/coverage-istanbul": 1.6.0
    "@vitest/coverage-v8": 1.6.0
    "@vitest/ui": 1.6.0
onlyBuiltDependencies:
  - "@biomejs/biome"
