name: Deploy

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types: [completed]
    branches: [main]

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: |
          cd apps/api
          pnpm build

      - name: Deploy to staging
        run: |
          echo "🚀 Deploying to staging environment..."
          echo "✅ Build completed successfully"
          echo "📦 Artifacts ready for deployment"
        # Aqui você pode adicionar comandos específicos para seu ambiente de staging
        # Por exemplo: docker build, kubectl apply, etc.

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: |
          cd apps/api
          pnpm build

      - name: Deploy to production
        run: |
          echo "🚀 Deploying to production environment..."
          echo "✅ Build completed successfully"
          echo "📦 Artifacts ready for production deployment"
        # Aqui você pode adicionar comandos específicos para seu ambiente de produção

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            ## 🚀 Production Release
            
            **Version:** v${{ github.run_number }}
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            
            ### ✅ What's included:
            - All tests passed
            - Code quality checks passed
            - Security audit passed
            - Build successful
            
            ### 📊 Test Coverage:
            - Value Objects: 100%
            - Employee Aggregate: 100%
            - Domain Integration: 100%
            
            ### 🔧 Changes:
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
